### ISSUE TITLE
Змінити колір значка додатку

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#1]
На даний момент колір значка є червоним.
Наш логотип помаранчевого кольору.
![Image of Yaktocat](https://lh4.googleusercontent.com/-ZyOMtDFUj0M/UneMWg0CBxI/AAAAAAAAcZk/3XjgtnpCdq4/s442/rivnefish.png)

Ось цей колір: #ffcc66

**Comment by lordmegamax** [comment]
Цей значок є у веркторному форматі?

**Comment by stal1n274** [comment]
Ось: https://www.dropbox.com/s/1nucx0lft7pt3ck/rr.pdf?dl=0

**Comment by lordmegamax** [comment]
Давай його яскравішим зробим? Цей колір дуже "ніякий"... І якщо поставить його також в ActionBar то аплікуха геть бліда...
![2015-03-18-19-11-11](https://cloud.githubusercontent.com/assets/2721556/6714719/83dd285c-cda2-11e4-89f5-20679913edf7.png)

 В андроїді прийнято користуватись більш яскравими кольорами і вибирать основні кольори для всієї апкі, тобто і маркери на карті повинні бути іншого кольору і решта елементів...
ось гайди: http://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by stal1n274** [comment]
Мені подобається такий колір. Як мінімум значок має бути таким.

Можливо це питання смаку, я не знаю. Нехай ще Ярослав відпишеться, як співзасновник проекту.

**Comment by stal1n274** [comment]
Таким м'якенький, пастельний колір. Він мене заспокоює, так і хочеться користуватись аплікейшеном :)

**Comment by h-yaroslav** [comment]
Можете замокапити з цим кольром: #fb8521

**Comment by h-yaroslav** [comment]
Мені помаранчеве подобається теж, і червоне теж.
Ну я би не проти глянути, як воно виглядає на телефоні. Навіть пропоную випустити апдейт а-ля "зміна кольорової схеми" і подивитися, а потім апдейт-реверт на червону.

**Comment by lordmegamax** [comment]
Це вже краще 
![2015-03-18 17 27 59](https://cloud.githubusercontent.com/assets/2721556/6715084/dee9b632-cda4-11e4-8269-2a36d97ce00f.png)

**Comment by h-yaroslav** [comment]
:+1:

**Comment by lordmegamax** [comment]
Робити #fb8521 основним кольором?

**Comment by lordmegamax** [comment]
І дайте мені значок в ілюстраторі або корелі, я з пдф нічого зробити не можу

**Comment by ttp** [comment]
нафіг вам той блідий жовтий? мені червоний більше подобається, або принаймі той темніший

**Comment by lordmegamax** [comment]
Давайте визначимось щоб потім не довелось все переробляти.

**Comment by stal1n274** [comment]
хай буде так: https://github.com/rivnefish/rivnefish_android/issues/1#issuecomment-83069260

**Comment by lordmegamax** [comment]
Все ще потрібно https://github.com/rivnefish/rivnefish_android/issues/1#issuecomment-83073733
