### ISSUE TITLE
Змінити поведінку фотографій до водойм

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#12]
1. Фото в горизонтальному положенні телефну є дуже розтягнутими, сприймати їх в такому вигляді важко.
2. Фото змінюються дуже швидко, потрібно збільшити інтервал між ними.
3. Чи можливо фотографії зробити клікабельними? Щоб роздивитись місцину ближче.

**Comment by lordmegamax** [comment]
// Фото в горизонтальному положенні телефну є дуже розтягнутими, сприймати їх в такому вигляді важко. 
Пофіксив в 4 версії

// Фото змінюються дуже швидко, потрібно збільшити інтервал між ними.
Поки це не можливо (ліба глючна)

// Чи можливо фотографії зробити клікабельними? Щоб роздивитись місцину ближче.
Поки ні, в ідеалі нам потрібно 2 фоткі щоб API давало - одна для превью і одна повного розміру. Всі тормоза слайдера через розміри фоток в 3Мб...

**Comment by stal1n274** [comment]
поки не закривай цей ішью, наш плагін зберігає в вордпресі не лише оригінальну картинку, але й її прев'юшки

спробую пошукати шлях до них в базі

**Comment by stal1n274** [comment]
Є можливість діставати з серверу прев'юшки, але вони всі розміром 100х75 пікселів. 
Не буде замаленьке?
Зате розмір до чотирьох кілобайт :)

Якщо влаштовує, то можна починати писати новий метод повернення окрему прев'ю кожного зображення.

**Comment by lordmegamax** [comment]
Це буде дуже маленьке зображення.
Поки нічого не пишіть, я спробую перейти на іншу лібу яка дозволяє робити превью вже на клієнті.

**Comment by lordmegamax** [comment]
Переробив з іншою лібою, додав блур на фон.

![2015-06-08-18-19-25](https://cloud.githubusercontent.com/assets/2721556/8038544/d359735e-0e0c-11e5-8f2c-ede4853a6fdf.png)
![2015-06-08-18-21-28](https://cloud.githubusercontent.com/assets/2721556/8038546/d637bfb8-0e0c-11e5-9824-991721b05e30.png)
