### ISSUE TITLE
Змінити виведення інформації про водойму: умови рибалки

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#13]
При кліку на водойму показувати користувачу умови рибалки.
Це виводить метод в API `paid_fish`

**Comment by lordmegamax** [comment]
> При кліку на водойму показувати користувачу умови рибалки.

Це мається на увазі при кліку маркера на карті?

**Comment by stal1n274** [comment]
Так, після кліку на маркер повинне з'являтись нове вікно, в якому окремо виводяться різні параметри водойми, в тому числі і умови рибалки

**Comment by lordmegamax** [comment]
Виводиться основним кольором.
![2015-06-08-18-44-21](https://cloud.githubusercontent.com/assets/2721556/8038859/af795696-0e0e-11e5-9faa-678286118e63.png)
