### ISSUE TITLE
Змінити виведення інформації про водойму: контакт на водоймі

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#14]
При кліку на водойму показувати користувачу контактний номер телефону.
Це виводить метод в API `contact`

**Comment by lordmegamax** [comment]
Зараз API видає щось на зразок: 

> contact=+380362233428. Це кому дуже хочеться поспілкуватись(цікаво про що?) з представниками УТМР.

Давайте розділим текст і номер(и) телефону? Наприклад передавати не просто текстом все, а в json об_єктом? Тоді можна буде зробити кнопку щоб користувач міг одразу набрати цей номер, а не переписував на листочок і потім набирав вручну...
Також можна додати кнопку "Додати в контакти" і брати телефон + ім_я людини.

Як вам така пропозиція?

**Comment by stal1n274** [comment]
Підтримую пропозицію, мені вона подобається.
Одне поле для телефону і інше поле для текстової примітки.

**Comment by lordmegamax** [comment]
Відпишіться, будь ласка, як буде готово.

**Comment by stal1n274** [comment]
Незабаром відпишусь, в базі даних вже все готово. Черга за методом API.

**Comment by stal1n274** [comment]
Метод готовий: https://github.com/rivnefish/rivnefish_api/issues/15
Будь ласка протестуєте чи все ок.
