### ISSUE TITLE
Змінити виведення інформації про водойму: стаття з водоймою

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#15]
При кліку на водойму показувати користувачу посилання на статтю про водойму на нашому сайті.
Це виводить метод в API `url`

**Comment by lordmegamax** [comment]
![2015-04-30-06-52-55](https://cloud.githubusercontent.com/assets/2721556/7414168/7d94267a-ef59-11e4-9c02-14deaf842db1.png)

**Comment by stal1n274** [comment]
Це не годиться, адже основний текст з описом може суттєво відрізнятись від того, що було завантажено в таблицю markers чотири роки тому :(

**Comment by lordmegamax** [comment]
А я що можу зробити? Редагуйте значить. Я роблю тонкий клієнт який показує те що повертає АРІ... При кліку на "Деталі" відкриється браузер по лінку

**Comment by stal1n274** [comment]
Потрібно виводити інформацію з бази даних як то: умови, риба, відпочинок, контакт і т.п. і аж в самому кінці можна виводити ось цей величезний текст з описом.

**Comment by stal1n274** [comment]
Кнопку "Деталі" я б перейменував на "Веб-сайт"

**Comment by lordmegamax** [comment]
> Потрібно виводити інформацію з бази даних як то: умови, риба, відпочинок, контакт і т.п. і аж в самому кінці можна виводити ось цей величезний текст з описом.

Як це стосується назви таску?

> Кнопку "Деталі" я б перейменував на "Веб-сайт"

Готово.

**Comment by stal1n274** [comment]
Чудово, спасибі.
