### ISSUE TITLE
Змінити дані Play Market

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish_android#16]
1. Опис (до 4к символів)
   "Рибні місця Рівненщини" — додаток для любителів активного відпочинку, тих для кого рибалка — це спорт, хобі чи просто гарний привід зустрітися з друзями. Тепер Вам не треба самим шукати місце для рибалки. Наша програма підкаже, де Ваша вудка стане в пригоді.
   У нас ви зможете знайти корисну інформацію від досвідчених рибалок, поділитися своїм досвідом або ж дізнатися, які снасті використовувати краще для тої чи іншої риби.
   Риболовля стане тепер зручнішою, адже ми відкриємо для Вас всі її секрети!
2. Значок в высоком разрешении 512 x 512
   https://lh3.googleusercontent.com/-JqO3hsv-KNY/VP9dyt95euI/AAAAAAAAwkY/chOn3CG2Jbc/s512/logo_512.png
3.  Значок для раздела "Рекомендуемые" 1024 x 500 (Ш x В)
   https://lh6.googleusercontent.com/-XQ0JE3-CfFU/VP9dyhZkGiI/AAAAAAAAwkU/FxtUv1Gulns/s1024/500x1024.png
4.  Рекламное изображение 180 x 120 (Ш x В) 
   https://lh5.googleusercontent.com/-P_QhhHm4Bws/VP9dyhNfe_I/AAAAAAAAwkM/EidpFktKHzc/s180/180x120.png

**Comment by lordmegamax** [comment]
// Рекламное изображение 180 x 120 (Ш x В) 
Серйозно? Просто розтягнутий значок?

// Значок для раздела "Рекомендуемые" 1024 x 500 (Ш x В)
Виглядає не особо... Треба якось більш до кольору апкі зробить, чи на фоні карти...

**Comment by stal1n274** [comment]
Ну, дизайнера ніякого іншого крім мене немає :)

якщо у тебе є якісь кращі варіанти, давай :8ball:

**Comment by lordmegamax** [comment]
З мене теж "не дизайнер" ;) Але якщо вже міняти графіку то на кращу, а не просто аби замінити.. Може є кого підключити з креативних людей?

**Comment by stal1n274** [comment]
я не знаю жодного рибака-дизайнера
в основному рибакі - це якісь хворі на голову люди, що кидають навіть роботу заради рибалки

здебільшого самі зайдлі працюють прямо в рибальських магазинах продавцями, або навіть живуть за рахунок інших і нічого робити не вміють окрім як ловити рибу і їздити по змаганням

мої пошуки людей в СофтСерві задля реалізації проекту рівнефіш лише через два роки принесли хоча б якісь незначні успіхі... і то ті хлопці що визвались допомагати навіть на рибалку і не їздять

**Comment by lordmegamax** [comment]
А дизайнери "не рибалки"? Або на форумі якусь тему створить по типу конкурса графіки?

**Comment by stal1n274** [comment]
ой мля.. там такого тобі понамальовують, що хоч стій хоч падай.
ось можеш подивитись: 
http://rivnefish.com/forum/viewtopic.php?f=1&t=1368
http://rivnefish.com/forum/viewtopic.php?f=1&t=425116
http://rivnefish.com/forum/viewtopic.php?f=655&t=1811

Але ми можемо спробувати знову ;)
який буде приз людині, яка намалює найгарніший малюнок?

**Comment by lordmegamax** [comment]
Давай спробуєм знову? Може хоч ідея якась виникне толкова...

**Comment by lordmegamax** [comment]
// який буде приз людині, яка намалює найгарніший малюнок?
Такий як і мені за андроїд апку ;)

**Comment by stal1n274** [comment]
Отже, нам потрібно на даний момент дві речі?
1. Значок для раздела "Рекомендуемые" 1024 x 500 (Ш x В)
2. Рекламное изображение 180 x 120 (Ш x В)

**Comment by lordmegamax** [comment]
Для початку так.

**Comment by stal1n274** [comment]
ну, побачимо чи хтось взагалі зголоситься допомогти: http://rivnefish.com/forum/viewtopic.php?f=108&t=425827

**Comment by lordmegamax** [comment]
Опублікував поки зміни тільки повного опису, якщо будуть рекламні зображення то відкриємо знову.
