### ISSUE TITLE
Список нових фіч

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish_android#18]
Пропоную складати всі цікаві ідеї для нових фіч сюди. 
Погоджені фічі можна додавати в issues для реалізації.

Наприклад:
- додавання звіту (що саме там має бути, як ви це уявляєте)
- оцінка водойми
- ...

**Comment by stal1n274** [comment]
1. Додавання водойми в базу. Як це реалізовано через веб: http://rivnefish.com/lakes/add-fish-place/
2. Додавання звіту про рибалку. Загалом я це бачу так: звіт додається до конкретної водойми. Як загалом людина оцінює рибалку, скільки риби зловленої і якої саме, опціонально написати пару слів, додати фоточки.

**Comment by stal1n274** [comment]
Виводити інформацію про те, чи платна водойма, чи безкоштовна, чи взагалі там ловити заборонено.

**Comment by stal1n274** [comment]
Інформація про особливості кльову конкретної риби на водоймі ніде не виводиться(поле notes):
![image](https://cloud.githubusercontent.com/assets/5851581/10640223/8034953a-781c-11e5-938d-0125aee6be22.png)

Також не виводяться ні середня/максимальна вага.

**Comment by stal1n274** [comment]
будемо робити окремі issue.
