### ISSUE TITLE
Опис програми в Google Play

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#19]
В Україні є 63029 річок, близько 1103 водосховищ, 49444 ставків, понад 20000 озер і лише одна програма Rivnefish, яка допоможе вам зорієнтуватись де ж ловити рибу у всьому цьому національному багатстві. 

Наш додаток про рибні місця рідного краю призначений для рибалок, які шукають для себе нові місця для вудіння риби і хочуть поділитись з іншими своїми звітами своїми знаннями та досвідом.

Віднині вам не потрібно ломати собі голову над тим, де ж знайти омріяну рибу. Ми вже подбали за все про вас. Лише за допомогою нашої програми вам буде доступна база даних рибних місць рідного краю з детальними описом, умовами відпочинку, сотнями фотографій і тисячами коментарів від інших рибаків.

**Comment by lordmegamax** [comment]
Замінив.
Ще є короткий опис (до 80 символів) який також можна придумати кращий. 
Зараз короткий опис "Клієнт для сайту http://rivnefish.com/"
