### ISSUE TITLE
Виводити більше інформації про рибу на водоймі

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#2]
API повертає інформацію про:
1. кльов
2. середню вагу
3. максимальну вагу
4. примітку

http://api.rivnefish.com/markers-fishes/?marker=2

```
        "weight_avg": 500, 
        "weight_max": 2500, 
        "amount": 3, 
        "notes": "горох на донках і бойли"
```

Ця інформація не відображається в додатку

**Comment by stal1n274** [comment]
Ось приклад, як дана інформація виводиться на сайті: http://rivnefish.com/lakes/bochanicya/

**Comment by lordmegamax** [comment]
Щось я не бачу по твому лінку де ця інформація на сторінці...

**Comment by stal1n274** [comment]
Відразу над текстом є значки риб з індикаторами кльову. При наведенні на них курсову миші з'являється інформація про розмір.

**Comment by lordmegamax** [comment]
Який параметр з http://api.rivnefish.com/markers-fishes/?marker=2 відповідає за кльов?

**Comment by stal1n274** [comment]
> Який параметр з http://api.rivnefish.com/markers-fishes/?marker=2 відповідає за кльов?

За цей параметр відповідає `amount`

Всі параметри:
`weight_avg` Середня вага потенційного улову(однієї рибини) в грамах
`weight_max` Максимальна вага потенційного улову(однієї рибини) в грамах
`amount` ймовірність впіймати рибу
`notes` примітка

**Comment by lordmegamax** [comment]
Яке максимальне значення може мати amount?

**Comment by stal1n274** [comment]
> Яке максимальне значення може мати amount?

10

**Comment by lordmegamax** [comment]
Тепер буде так:

![2015-03-24 15 46 25](https://cloud.githubusercontent.com/assets/2721556/6805834/c687f31c-d24d-11e4-9556-b77527c7071a.png)

**Comment by stal1n274** [comment]
1. Чому індикатор ймовірності впіймати рибу не зробити таким же, як на сайті? Я маю на увазі колір та місцеположення індикатору
   ![image](https://cloud.githubusercontent.com/assets/5851581/6806381/17a9db22-d251-11e4-9306-f7688d777fc9.png)
2. Де буде відображено середню і максимальну вагу? Нотатка? Чи це планується зробити в наступних версіях?
3. Чи можна змінити відображення назв риб з "ukr_name" до "name" ?

**Comment by lordmegamax** [comment]
1. Тому що це не веб.
   2-3. При натисканні на рибу буде діалогове вікно з повною інформацією.
