### ISSUE TITLE
Доступ до маркерів без інтернет-з'єднання

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#21]
Їде людина день в безлюдних місцях. Далеко від цивілізації та інтернету. Захотілось їй покористуватись нашою мапою з рибними точками. А звязку з сервером немає. 
В такому випадку їй повинна показуватись остання доступна їй база даних поплавків, які були завантажені в попередній сесії.

Також, кожного разу не потрібно завантажувати всю базу заново на телефон.
При запуску аплікації з доступним інтернет з'єднанням потрібно перевіряти чи не змінився хеш на сервері, якщо так - то завантажити базу заново. Суміжне іш'ю: https://github.com/rivnefish/rivnefish_api/issues/3

**Comment by lordmegamax** [comment]
Ти хочеш бачити поплавкі на карті з локальної бази чи інформацію по водоймах які юзер відкривав?

Якщо тільки поплавкі то можна закривати цей таск, воно і так вже працює.

**Comment by stal1n274** [comment]
Тут малось на увазі саме поплавки на мапі без інтернету.

Воркфлов такий: 
1. Перевірити чи є доступ до сервера, якщо немає - виводити збережені поплавки.
2. Порівняти збережений хеш з хешем на сервері
3. Якщо хеш однаковий - виводити збережені поплавки.
4. Якщо хеш різний - завантажити всі поплавки з серверу.

Питання: чи можемо ми кешувати інформацію на девайсі рибних місць, по яких вже ходив користувач? Щоб теж виводити їх локально, кожен раз не дьоргаючи інфу з серверу?

**Comment by lordmegamax** [comment]
// Тут малось на увазі саме поплавки на мапі без інтернету.
Воно давно так і працює.

//  чи можемо ми кешувати інформацію на девайсі рибних місць, по яких вже ходив користувач? Щоб теж виводити їх локально, кожен раз не дьоргаючи інфу з серверу?
Поки не бачу в цьому змісту. Всеодно при кожному відкритті поплавка потрібно перевіряти чи є оновлення то простіше зразу все стягнути, враховуючи що зображення і так кешуються.

**Comment by ttp** [comment]
дуже незручно не мати доступу до маркерів офлайн, перевірено на собі

**Comment by stal1n274** [comment]
Все працює гарно, маленьке побажання: кешувати ще й зображення водойм, як це робиться в iOS додатку
