### ISSUE TITLE
Додати інформацію про рибу на водоймі

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#24]
Інформація про особливості кльову конкретної риби на водоймі ніде не виводиться(поле notes):
![image](https://cloud.githubusercontent.com/assets/5851581/10640223/8034953a-781c-11e5-938d-0125aee6be22.png)

Також не виводяться ні середня/максимальна вага.
Цю інформацію повертає метод http://api.rivnefish.com/markers-fishes/

**Comment by lordmegamax** [comment]
weight & notes - виводяться в діалоговому вікні по кліку на рибу.
amount - я так розумію що це шанс впіймати, він виводиться під зображенням у вигляді progressbar'a.

**Comment by stal1n274** [comment]
Макс, додай в це віконечко також і ймовірність впіймати рибу на цій водоймі
Це буде логічно мати всю інформацію в про конкретну рибу обраної водоймі в одному місці.

Дякую!

**Comment by stal1n274** [comment]
Я вважаю, що в цьому вікні не варто виводити загальну інформацію про рибу, треба придумати для цього інше місце:

![image](https://cloud.githubusercontent.com/assets/5851581/16547362/bd0d1c04-4173-11e6-8e7d-3e759fab7424.png)
