### ISSUE TITLE
Add 'share' option

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish_android#25]
Пропоную шарити дані водойми з додаванням rivnefish.com в кінці.
Яку саме інформацію було б корисно шарити?

**Comment by stal1n274** [comment]
А що ти маєш на увазі під розшаренням? Викладання посилання на водйому в фейсбуці, чи як?

Головна інформація про водойму:
1. Назва
2. Умови риболовлі
3. Фото
4. Рейтинг водойми (ще не реалізовано)

**Comment by stal1n274** [comment]
fixed and verified
