### ISSUE TITLE
Виводити кружечки для зображень водойми

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#29]
Користувач може й не підозрювати, що до водойми завантажено кілька фотографій.
Потрібно реалізувати ось такі ось ідентифікатори:
![image](https://cloud.githubusercontent.com/assets/5851581/18268144/4238df64-742b-11e6-9e54-53d72d96c8af.png)
Якщо мені не зраджує пам'ять, то це колись вже було реалізовано в додатку для андройду, і тепер кудись все пропало. Тому можливо це баг :)

**Comment by lordmegamax** [comment]
нова галерея, вже не актуально
