### ISSUE TITLE
Змінити виведення інформації про водойму

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#3]
Ось так я уявляю нове вікно з водоймою, яке відкривається користувачу після кліку на маркер:
![image](https://cloud.githubusercontent.com/assets/5851581/6690694/b75f26a4-ccca-11e4-92f7-78142d68ccfd.png)

**Comment by lordmegamax** [comment]
фотки по центру екрану? це якось не по мобільному...

**Comment by stal1n274** [comment]
Нехай фото будуть на тому місці, що й зараз.

**Comment by lordmegamax** [comment]
Для того щоб зробити клікабельним телефон потрібна валідаця в API бо воно повертає в довільній формі то contact=(0362)5-22-20, 067-363-61-32 то один номер без дужок то пусте значення то null...

**Comment by stal1n274** [comment]
Оскільки наші користувачі почали жалітись на те, що дані про водойми неактуальні, потрібно імплементувати цю фічу скоріше. 

Можливо варто розбити її на декілька простіших?

**Comment by lordmegamax** [comment]
Ну створюй тоді окремі завдання...

**Comment by stal1n274** [comment]
Першочергові характеристики водойм:
https://github.com/rivnefish/rivnefish_android/issues/13
https://github.com/rivnefish/rivnefish_android/issues/14
https://github.com/rivnefish/rivnefish_android/issues/15

Після реалізації цього, треба буде додати:
площа ставка, глибини, умови відпочинку, коли дозволено ловити, інформація про човен.

**Comment by lordmegamax** [comment]
Може цю біду зробити вкладками? 
Основна інформація, Риба, Фото, Умови і контакти...

Бо виходить якщо текст великий то забагато скролити, а якщо маленький то виглядає не гарно...

**Comment by stal1n274** [comment]
Я не справжній ~~електросварщик~~ дизайнер, тому не знаю як було б краще. 
Давай може спочатку будемо виводити все табличкою і глянемо як воно буде :)

**Comment by lordmegamax** [comment]
Краще зразу продумать щоб не перероблювати бо часу ітак нема.

Робим вкладками?

**Comment by stal1n274** [comment]
Ну давай вже з вкладками, але якщо рибалкам не сподобається, то переробимо :)
