### ISSUE TITLE
Використовувати кеш. Доступ до маркерів без інтернет-з'єднання.

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#30]
Їде людина день в безлюдних місцях. Далеко від цивілізації та інтернету. Захотілось їй покористуватись нашою мапою з рибними точками. А зв'язку з сервером немає. 
В такому випадку їй повинна показуватись остання доступна їй база даних поплавків, які були завантажені в попередній сесії.

На даний момент без інтернету просто з'являється напис: "Немає зв'язку з сервером"

Також, кожного разу не потрібно завантажувати всю базу заново на телефон.
При запуску аплікації з доступним інтернет з'єднанням потрібно перевіряти чи не змінився хеш на сервері, якщо так - то завантажити базу заново.

І пропоную кожного разу не завантажувати всі маркери з серверу, а зберігати їх локально на телефоні під час однієї сесії. От приклад: відкрити якусь водойму, і вимкнути інтернет. Натисну кнопку "Назад", щоб повернутись на мапу. Нічого не загрузиться.

**Comment by lordmegamax** [comment]
зроблено, релізим в 0.7
