### ISSUE TITLE
На клік одночасно і попап і одразу водойму відкриває

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#39]
Пропоную відкривати лише попав з назвою і рейтингом водойми, а повторний клік на цей попап хай вже відкривав би детальну інформацію.

Нагадаю, що в попередній версії попапу взагалі не було, а в ІОСі у нас спочатку попап і потім вже детальна інфа при повторному кліку.

**Comment by lordmegamax** [comment]
Наскільки я розумію на даному етапі в нас нема рейтингу водойми від сервера

{
	"id": 24,
	"name": "Бельмаж",
	"lat": "50.31617",
	"lng": "26.496469",
	"updated_at": "2016-12-21T22:42:31.106Z"
}

і чи є взагалі зміст показувати попапом тільки назву? може краще одразу відкривати деталі без попапу?

**Comment by stal1n274** [comment]
Я хочу, щоб на попапі був присутній рейтинг, якщо є хоча б одна оцінка.

Не розумію, який метод тобі повернув так обмаль інформації?
Ось список всіх доступних методів: https://github.com/rivnefish/rivnefish/wiki/API-methods

Коли я хочу подивитись інформацію про водойму з id=24:
http://new.rivnefish.com/api/v1/places/24

Там же присутній і рейтинг:

{
	"id": 24,
	"name": "Бельмаж",
	"lat": "50.31617",
	"lng": "26.496469",
	"area": null,
	"depth_avg": null,
	"depth_max": null,
	"permit": "paid",
	"time_to_fish": "full_day",
	"price_24h": null,
	"price_day_only": null,
	"price_notes": "50 грн. ",
	"boat_usage": false,
	"address": null,
	"notes": null,
	"conveniences": null,
	"contact_phone": "380961712728",
	"contact_name": "Сергій",
	**"rating_avg": "3.0",
	"rating_votes": 1,**
	"photos": [],
	"updated_at": "2016-12-21T22:42:31.106Z",
	"info_updated_at": "2013-07-23T09:28:00.000Z",
	"description": null,
	"url": "http://new.rivnefish.com/places/24",
	"place_fishes": []
}

**Comment by lordmegamax** [comment]
Це погана практика в андроїді по кліку на маркер робити запит на сервер, імовірність що данні вже кешовані досить мала, а при повільному інтернеті (що зазвичай і буває) буде дивний UX коли юзер клікнув і нічого не відбуваєьтся кілька секунд...

**Comment by stal1n274** [comment]
Тоді по кліку нехай відразу впливає попап, де пишеться назва місця (яка вже є в пам'яті), а рейтинг підзавантажується. Якщо не завантажиться - нічого страшного, користувач вже бачить, як називається його точка і він може клікнути, щоб дізнатись більше.

**Comment by lordmegamax** [comment]
Подивлюсь чи так можна зробити, але як про мене то це не зручно. Далеко не всі користувачі здогадаються повторно тицьнути на попап... І це ще одна додаткова дія..

**Comment by ttp** [comment]
Як прийнято я хз, але мені не подобається, що відбуваються обидві дії одночасно, тобто відкривається попап і одразу поверх нього відкривається вже вся сторінка із місцем.
І я за те щоб робити однакову поведінку на іос/андроїд. Я можу повертати і рейтинг у всіх точках якщо потрібно.
Дивлюсь на гугл картах, вони на клік показують маленький бар знизу, щоб показати по чому ти клікнув(на багатьох інших картах так само), і лише після кліку по ньому відкривається повна інфа. І вони підвантажують інфу по кліку, тобто показуть бар і в ньому прописана одразу назва і йде завантаження рейтингу.

**Comment by lordmegamax** [comment]
> Я можу повертати і рейтинг у всіх точках якщо потрібно.

Це було б дуже зручно і не вимагало б багато додаткового трафіку

> Дивлюсь на гугл картах, вони на клік показують маленький бар знизу, щоб показати по чому ти клікнув(на багатьох інших картах так само), і лише після кліку по ньому відкривається повна інфа.

Тепер я зрозумів що мається на увазі, спробую знайти як таке реалізувати.

**Comment by stal1n274** [comment]
Тепер з'являється плашка внизу екрану з головною інформацією про водойму
