### ISSUE TITLE
Змінити назву додатку

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#4]
на даний момент: 
`Rivnefish online`

змінити на: 
`Rivnefish: рибні місця рідного краю`

**Comment by lordmegamax** [comment]
Якщо ти маєш на увазі назву на плей маркеті то ми не влазим по кількості символів. Максимально можна 30, а в тебе 35.

**Comment by stal1n274** [comment]
Rivnefish: рибні місця
