### ISSUE TITLE
Перейменвати ось цю сторінку з рибою

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#49]
"Список риби"
->
"Риба, що тут водиться" або "Риба в рибному місці Кричевичі" або "Риба" або "Що ловиться?"

**Comment by stal1n274** [comment]
Приклад як це зроблено в додатку для айфонів:

![image](https://user-images.githubusercontent.com/5851581/33343462-0877c17c-d48e-11e7-9b70-8a6786db773d.png)

**Comment by lordmegamax** [comment]
"Риба, що тут водиться"
