### ISSUE TITLE
Додаток неочікувано завершує свою роботу, якщо двічі змінити орієнтацію пристрою

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#5]
кроки для відтворення:
1. Запустити програму в вертикальному положенні пристрою
2. Відкрити будь яку водойму
3. Перевести пристрій в горизонтальне положення
4. Перевести пристрій в вертикальне положення положення

Пробував на двох різних телефонах, один якась моторолла, інший леново. Версій ОС не знаю.

**Comment by lordmegamax** [comment]
Fixed.
