### ISSUE TITLE
Тест

### ISSUE THREAD

**Issue by tornvald** [rivnefish/rivnefish_android#54]
1. В таблице данных по водоему нет единиц измерения.
2. Для чего нужна кнопка на тулбаре в виде земного шара?
3. Как добавить отчет и откуда берется рейтинг?
4. контактная информация о владельцах/предоставителей услуг сделана как попало и неодинаково

**Comment by stal1n274** [comment]
Доброго дня, tornvald!

Приємно, що ви виявили інтерес до нашого маленького проекту.
Ми готуємо з дня на день новий реліз під Andoid, в якому аплікація буде переписана просто з нуля :)
Сподіваюсь, що тоді всі ці питання у вас вирішаться самі собою. Єдине, на що можна вже зараз дати відповідь це те, що звіти з рибалки поки що вносяться лише через веб-сайт: https://rivnefish.com/reports/new
В кожного такого звіту є свій рейтинг, на основі середнього арифметичного й формується загальний рейтинг водойми по цих звітах.

Дякуємо за небайдужість!

**Comment by stal1n274** [comment]
Нова версія програми вже доступна для завантаження. Ваші зауваження ми врахуємо в наступних релізах. 
1. зробив окремо дефект репорт https://github.com/rivnefish/rivnefish_android/issues/55
2. для переходу на вебсайт з описом цієї водойми
3. додавання звіту буде в наступних версіях програми
4. щоб реалізувати це потрібно трохи добряче переробити існуючу базу даних, але в планах це також є

Ще раз дякуємо!
