### ISSUE TITLE
Не виводити водойми у яких approval="rejected"

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish_android#6]
Наші користувачі додають водойми на мапу. 
Якщо якість інформації в них низька, ми їх відкидаємо і не виводимо. 
За це відповідає поле `approval` воно має три значення:
1. approved
2. pending
3. rejected

Відображати в додатку потрібно лише водойми з статусом `approved`

Як приклад можеш подивитись водойму з id=377

**Comment by lordmegamax** [comment]
Яке відношення до цього має андроїд? Це повинно робити API.

**Comment by ttp** [comment]
Погоджуюсь. Тип маркерів, що повертається має визначатись правами користувача.  Тобто користувач, токен якого юзає андроїд, має мати таку роль, яка дозволяє йому бачити лише апрувнуті маркери. Такий собі policy scope.

**Comment by stal1n274** [comment]
https://github.com/rivnefish/rivnefish/issues/10
