### ISSUE TITLE
Додати можливість прокласти маршрут від теперішнього місцезнаходження

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish_android#8]

**Comment by stal1n274** [comment]
На мою особисту думку(а вона може бути хибною) при кліку на маркер з головної карти не має відразу відображатись детальна інформація водойми.
Спочатку має намалюватись міні-віконечко прямо на мапі в якому:
1. Має бути назва водойми
2. Індиактор кльову(популярності). _Це поки що не реалізовано на боці сервера._
3. Кілька клікабельних лінків:
 а) Детальна інформація про цю водойму
 б) Додати звіт з рибалки
 в) Почитати всі звіти з рибалки
 г) **Прокласти маршрут до цього місця**

**Comment by lordmegamax** [comment]
Стільки інфи в infoWindow не влізе однозначно - уяви як воно буде виглядати на екрані в 3".
Стосовно клікабельності infoWindow - я можу хендлити тільки клік по infoWindow , а не по кнопкам чи лінкам в ньому. Тобто на клік можна повісити тільки одну операцію.

Виходить що або не буде деталей водойми або не ясно куди поставить кнопку "прокласти маршрут"

**Comment by lordmegamax** [comment]
Пропоную додати кнопку в ActionBar в деталях водойми. При натисненні буде повертатись на карту і показувати маршрут.

![2015-03-26-05-09-01](https://cloud.githubusercontent.com/assets/2721556/6845917/24d27a30-d3c2-11e4-92e5-3b958d68ecf2.png)

**Comment by stal1n274** [comment]
Поки що можна додати й тут, але я бачу це в іншому місці :)
Але то виходить за межі даного issue, обговоримо в майбутньому.

**Comment by lordmegamax** [comment]
Давай не будемо робити "покищо"? Витрачати час щоб все потім перероблювати я не хочу, тим більше це не комерційна апка.

**Comment by lordmegamax** [comment]
Реалізував тимчасово використовуючи встановлену зовнішню гугл карту.

![2015-04-06-16-51-55](https://cloud.githubusercontent.com/assets/2721556/7005096/7bccbdaa-dc7d-11e4-8ef6-6a8e270e7c57.png)
