### ISSUE TITLE
Реалізувати перевірку актуальності даних

### ISSUE THREAD

**Issue by lordmegamax** [rivnefish/rivnefish_android#9]
https://github.com/rivnefish/rivnefish/issues/3

**Comment by stal1n274** [comment]
Це ще актуально? Щось потрібно робити?

**Comment by lordmegamax** [comment]
Так, https://github.com/rivnefish/rivnefish/issues/3#issuecomment-89974213

**Comment by lordmegamax** [comment]
Тепер дані беруться з веба тільки тоді коли не співпадає локальне значення з тим що дає сервер. Якщо однакове - використовується локальний кеш маркерів з бази.
